[package]
name = "advent_of_code_2018"
version = "0.1.0"
authors = ["Ben Simms <ben@bensimms.moe>"]
edition = "2018"

[dependencies]
aoc-runner = "0.1.0"
aoc-runner-derive = "0.1.3"
int_hash = "0.1.1"
itertools = "0.7.11"
